paths:
  zip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2022/ZIPDATA'
  unzip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2022/UNZIPDATA'
  exopath: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2022/RawData'
  filepath: '.'

readprofile: False # read datafile on filepath folder

files:
  datafile: 'Data_20220429.csv'
    #unzip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2021/RawData'
