paths:
  zip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2021/ZIPDATA'
  unzip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2021/UNZIPDATA'
  exopath: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2021/RawData'
  filepath: '.'

readprofile: False # read datafile on filepath folder

files:
  datafile: 'Data_20211203.csv'
    #unzip: '/home/cesar/Dropbox/Cesar/PhD/Data/Mauritius/2021/RawData'
